// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewarjijmtfpuylybfzgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3YXJqaWptdGZwdXlseWJmemdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3Nzg2MTYsImV4cCI6MjA2NDM1NDYxNn0.tnDWxa-iQfSw_QPtkgI4n5H1MwqCmnxqzEIgVsH0keg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);